server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: testing-service
          uri: lb://auth-service
          predicates:
            - Path=/testing/**
          filters:
            - StripPrefix=0    
        - id: jwks-endpoint
          uri: lb://auth-service
          predicates:
            - Path=/.well-known/jwks.json
          filters:
            - RewritePath=/.well-known/jwks.json, /auth/.well-known/jwks.json
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1  

# Remove this - it's not needed for gateway configuration
# jwt:
#   public-key-endpoint: http://auth-service:8081/auth/.well-known/jwks.json
#   issuer: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka