server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Prashantkhamitkar/microservices-config-repo
          default-label: main
          clone-on-start: true
          search-paths: '{application}'
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always