spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
security:
  jwt:
    public-key-path: classpath:public_api_key.pem      
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
gateway:
  jwks-uri: http://localhost:8080/.well-known/jwks.json
logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth: DEBUG    
